# General structure:
# "<key>" => Dict("inner_diameter" => <n>,
#                 "outer_diameter" => <n>,
#                 "width" => <n>)


const ball_bearings_dict = Dict{ASCIIString, Dict}(
"683zz" => Dict("inner_diameter" => 3.0mm,
                "outer_diameter" => 7.0mm,
                "width" => 3.0mm),
"693zz" => Dict("inner_diameter" => 3.0mm,
                "outer_diameter" => 8.0mm,
                "width" => 4.0mm),
"603zz" => Dict("inner_diameter" => 3.0mm,
                "outer_diameter" => 9.0mm,
                "width" => 5.0mm),
"623zz" => Dict("inner_diameter" => 3.0mm,
                "outer_diameter" => 10.0mm,
                "width" => 4.0mm),
"684zz" => Dict("inner_diameter" => 4.0mm,
                "outer_diameter" => 9.0mm,
                "width" => 4.0mm),
"694zz" => Dict("inner_diameter" => 4.0mm,
                "outer_diameter" => 11.0mm,
                "width" => 4.0mm),
"604zz" => Dict("inner_diameter" => 4.0mm,
                "outer_diameter" => 12.0mm,
                "width" => 4.0mm),
"624zz" => Dict("inner_diameter" => 4.0mm,
                "outer_diameter" => 13.0mm,
                "width" => 5.0mm),
"634zz" => Dict("inner_diameter" => 4.0mm,
                "outer_diameter" => 16.0mm,
                "width" => 5.0mm),
"625zz" => Dict("inner_diameter" => 5.0mm,
                "outer_diameter" => 16.0mm,
                "width" => 5.0mm),
"685zz" => Dict("inner_diameter" => 5.0mm,
                "outer_diameter" => 11.0mm,
                "width" => 5.0mm),
"695zz" => Dict("inner_diameter" => 5.0mm,
                "outer_diameter" => 13.0mm,
                "width" => 4.0mm),
"605zz" => Dict("inner_diameter" => 5.0mm,
                "outer_diameter" => 14.0mm,
                "width" => 5.0mm),
"625zz" => Dict("inner_diameter" => 5.0mm,
                "outer_diameter" => 16.0mm,
                "width" => 5.0mm),
"635zz" => Dict("inner_diameter" => 5.0mm,
                "outer_diameter" => 19.0mm,
                "width" => 6.0mm),
"686zz" => Dict("inner_diameter" => 6.0mm,
                "outer_diameter" => 13.0mm,
                "width" => 5.0mm),
"696zz" => Dict("inner_diameter" => 6.0mm,
                "outer_diameter" => 15.0mm,
                "width" => 5.0mm),
"606zz" => Dict("inner_diameter" => 6.0mm,
                "outer_diameter" => 17.0mm,
                "width" => 6.0mm),
"626zz" => Dict("inner_diameter" => 6.0mm,
                "outer_diameter" => 19.0mm,
                "width" => 6.0mm),
"687zz" => Dict("inner_diameter" => 7.0mm,
                "outer_diameter" => 14.0mm,
                "width" => 5.0mm),
"697zz" => Dict("inner_diameter" => 7.0mm,
                "outer_diameter" => 17.0mm,
                "width" => 5.0mm),
"607zz" => Dict("inner_diameter" => 7.0mm,
                "outer_diameter" => 19.0mm,
                "width" => 6.0mm),
"627zz" => Dict("inner_diameter" => 7.0mm,
                "outer_diameter" => 22.0mm,
                "width" => 7.0mm),
"688zz" => Dict("inner_diameter" => 8.0mm,
                "outer_diameter" => 16.0mm,
                "width" => 5.0mm),
"698zz" => Dict("inner_diameter" => 8.0mm,
                "outer_diameter" => 19.0mm,
                "width" => 6.0mm),
"608zz" => Dict("inner_diameter" => 8.0mm,
                "outer_diameter" => 22.0mm,
                "width" => 7.0mm),
"689zz" => Dict("inner_diameter" => 9.0mm,
                "outer_diameter" => 17.0mm,
                "width" => 5.0mm),
"699zz" => Dict("inner_diameter" => 9.0mm,
                "outer_diameter" => 20.0mm,
                "width" => 6.0mm))
